### ISSUE TITLE
IT should be able to view, create and delete computers

### ISSUE THREAD

**Issue by kimberly-bird** [talkative-tangs/Bangazon-LLC#8]
## Acceptance Criteria

**Given** a user wants to view all computers
**When** the user clicks on the Computers item in the navigation bar
**Then** the user should see a list of all computers
**And** each item should be a hyperlink that can be clicked to view the details
**--Completed--**

**Given** a user is viewing all computers
**When** the user clicks the Create New link
**Then** the user should be presented with a form in which the following information can be entered

1. Computer manufacturer
1. Computer make
1. Purchase date
**--Completed--**

**Given** user is viewing a single computer
**When** the user clicks on the Delete link
**Then** the user should be presented with a screen to verify that it should be deleted
**And** if the user chooses Yes from that screen, the computer should be deleted **only if it is has never been assigned to an employee**
**--Completed--**

## Testing Criteria

* Your test suite must verify that the content of the responses contain all required input fields, where appropriate.
**--Completed--**
* Your test suite must verify that when a POST operation is performed to the corresponding URL, then a successful response is received. Status code must be 200.
**--Completed--**
* Your test suite must verify that when a DELETE operation is performed to the corresponding URL, then a successful response is received. Status code must be 200.
**--Completed--**

**Comment by laboyd001** [comment]
User is now able to:
view a list of computers,
view computer details,
add a new computer

Testing now includes:
making sure a computer appears in the computer list,
verifying that the correct inputs are on the add computer form,
verifying that the correct data posts to the DB

**Comment by laboyd001** [comment]
User is now able to delete a computer only if it has never been assigned.
Test suite now contains a test for delete.

**Comment by ousamasama** [comment]
went over all issue/testing requirements and confirmed functionality. moving to completed.
